kind = "api"
previewPath = "/casting"
title = "Casting Page"
version = "1.0.0"
id = "casting-kaseet-2026-v1"

[[services]]
localPort = 3333
name = "Casting Server"
paths = ["/casting"]

[services.development]
run = "pnpm --filter @workspace/casting run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/casting", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["node", "--enable-source-maps", "artifacts/casting/dist/index.mjs"]

[services.production.run.env]
PORT = "3333"
NODE_ENV = "production"

[services.production.health.startup]
path = "/healthz"
